### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by jbperkins** [ekussberg/simple-credits#2]
I'm getting a 404 error when I click on "Are you sure you want to buy this product? / Yes"
Anybody have any ideas how to fix this? Thanks

**Comment by ekussberg** [comment]
It can be that your WP is installed on some subdomain with wrong URL routing. Please check the path to the file of the ajax.php

**Comment by jbperkins** [comment]
Edgar, thanks for your help with this. My URL routing and path to the file seem to be correct. Do you think there is a wordpress or woocommerce setting that I need to change? Is there a special server requirement for this to work. Looks like a great plugin. Thanks again for any suggestions.

**Comment by 4tified** [comment]
I had this problem as well, but then I realized that after downloading the zip off of Github, it was called simple-credits-master, and made a folder of the same name in /wp-content. The issue is that "/wp-content/plugins/simple-credits/js/woocommerceCredit.js" looks for the ajax.php file as an absolute filepath of params.homeurl+'/wp-content/plugins/simple-credits/ajax.php'. If you have the plugin folder as any other name, it won't find ajax.php.

So, to fix this issue, simply rename the folder under /wp-content, "simple-credits"

Meanwhile, it might be useful to recode the woocommerceCredit.js file to point to the ajax.php relatively. Hope this helps! :)

**Comment by jbperkins** [comment]
Thanks for the help 4tified. Good work.

**Comment by ekussberg** [comment]
@4tified you are free to make a contribution and update it ;)
